"""init db

Revision ID: 20b0a71f49af
Revises: 
Create Date: 2023-05-17 00:39:01.059409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b0a71f49af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('type_request', sa.String(), nullable=False),
    sa.Column('add_datetime', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('stage_building', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('time_to_call', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_requests')
    # ### end Alembic commands ###
