"""add datetime col

Revision ID: a4edb6e0d72e
Revises: bb916a83b2bb
Create Date: 2023-05-18 04:47:46.849588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4edb6e0d72e'
down_revision = 'bb916a83b2bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_requests', sa.Column('add_datetime', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_requests', 'add_datetime')
    # ### end Alembic commands ###
