"""added  property_type

Revision ID: bb916a83b2bb
Revises: 20b0a71f49af
Create Date: 2023-05-17 05:01:14.322068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb916a83b2bb'
down_revision = '20b0a71f49af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_requests', sa.Column('property_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_requests', 'property_type')
    # ### end Alembic commands ###
